BulkyBookWeb/Areas/Admin/Controllers/CategoryController.cs
using BukyBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace BulkyBookWeb.Controllers

{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        //GET

        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            //CUSTOM VALIDATION
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Display Order and Name can't have same value");
            }
            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(obj);
                _unitOfWork.Save();
                TempData["success"]="Category created succesfully";
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           // var categoryFromDb = _db.Categories.Find(id);
             var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id == id);
            // var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            //CUSTOM VALIDATION
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The Display Order and Name can't have same value");
            }
            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(obj);
                _unitOfWork.Save();
                  TempData["success"]="Category updated succesfully";
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id == id);
            // var categoryFromDbFirst = _db.Categories.FirstOrDefault(u=>u.Id == id);
            // var categoryFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _unitOfWork.Category.GetFirstOrDefault(u=>u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
              TempData["success"]="Category deleted succesfully";
            return RedirectToAction("Index");

        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BukyBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    [Authorize]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;     

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
          //  IEnumerable<Company> objCompanyList = _unitOfWork.Company.GetAll();
            return View();
        }

        //GET

        public IActionResult Create()
        {
            return View();
        }
        //POST


        //GET
        public IActionResult Upsert(int? id)
        {
            /* Approach to access data from controller to view model
             * Company Company = new Company();
             IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select(
                 u => new SelectListItem
                 {
                     Text = u.Name,
                     Value = u.Id.ToString(),
                 });
             Another Approach to access data from controller to view model
             IEnumerable<SelectListItem> CoverTypeList = _unitOfWork.CoverType.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
            */
            Company Company = new();
            
            if (id == null || id == 0)
            {
                
                return View(Company);
            }
            else
            {
                Company = _unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
                return View(Company);
                //update
            }
             
            return View(Company);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company obj)
        {

            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
               
                if(obj.Id==0)
                {
                    _unitOfWork.Company.Add(obj);
                    TempData["success"] = "Company created succesfully";
                }
                else
                {
                    _unitOfWork.Company.Update(obj);
                    TempData["success"] = "Company updated succesfully";
                }

                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var CompanyList = _unitOfWork.Company.GetAll();
            return Json(new { data = CompanyList });
        }
        [HttpDelete]
       // [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);   
            if(obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Company.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Company deleted  succesfully" });
        }
        #endregion
    }

}

BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BukyBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    [Authorize]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypeList = _unitOfWork.CoverType.GetAll();
            return View(objCoverTypeList);
        }

        //GET

        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            //CUSTOM VALIDATION

            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"]="CoverType created succesfully";
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
           // var CoverTypeFromDb = _db.Categories.Find(id);
             var CoverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id == id);
            // var CoverTypeFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (CoverTypeFromDb == null)
            {
                return NotFound();
            }
            return View(CoverTypeFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            //CUSTOM VALIDATION

            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                  TempData["success"]="CoverType updated succesfully";
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var CoverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id == id);
            // var CoverTypeFromDbFirst = _db.Categories.FirstOrDefault(u=>u.Id == id);
            // var CoverTypeFromDbSingle = _db.Categories.SingleOrDefault(u=>u.Id==id);
            if (CoverTypeFromDb == null)
            {
                return NotFound();
            }

            return View(CoverTypeFromDb);
        }
        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.CoverType.Remove(obj);
            _unitOfWork.Save();
              TempData["success"]="CoverType deleted succesfully";
            return RedirectToAction("Index");

        }
    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BukyBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;       

        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment; 
        }

        public IActionResult Index()
        {
          //  IEnumerable<Product> objProductList = _unitOfWork.Product.GetAll();
            return View();
        }

        //GET

        public IActionResult Create()
        {
            return View();
        }
        //POST


        //GET
        public IActionResult Upsert(int? id)
        {
            /* Approach to access data from controller to view model
             * Product product = new Product();
             IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select(
                 u => new SelectListItem
                 {
                     Text = u.Name,
                     Value = u.Id.ToString(),
                 });
             Another Approach to access data from controller to view model
             IEnumerable<SelectListItem> CoverTypeList = _unitOfWork.CoverType.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                });
            */
            ProductVM ProductVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(
                 u => new SelectListItem
                 {
                     Text = u.Name,
                     Value = u.Id.ToString(),
                 }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(
                u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString(),
                }),
            };
            if (id == null || id == 0)
            {
                //create
               // ViewBag.CategoryList = CategoryList;
               // ViewData["CoverTypeList"] = CoverTypeList;
                return View(ProductVM);
            }
            else
            {
                ProductVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
                return View(ProductVM);
                //update
            }
             
            return View(ProductVM);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM obj,IFormFile? file)
        {

            //SERVER VALIDATION
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString(); 
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extension = Path.GetExtension(file.FileName);

                    if(obj.Product.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads,fileName+extension),FileMode.Create))
                    {
                        file.CopyTo(fileStreams);   
                    }
                    obj.Product.ImageUrl = @"images\products\" + fileName + extension;

                }
                if(obj.Product.Id==0)
                {
                    _unitOfWork.Product.Add(obj.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(obj.Product);
                }

                _unitOfWork.Save();
                  TempData["success"]="Product created succesfully";
                return RedirectToAction("Index");
            }

            //VALIDATION FAILED
            return View(obj);

        }



        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new { data = productList });
        }
        [HttpDelete]
       // [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            var obj = _unitOfWork.Product.GetFirstOrDefault(x => x.Id == id);   
            if(obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(obj);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Product deleted  succesfully" });
        }
        #endregion
    }

}

BulkyBookWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BulkyBook.Utility
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Bookify</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/bootswatchTheme.css" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
	<link rel="stylesheet" href="~/css/index.css" />

	<!-- CSS only -->
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">*@
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light app-nav">
			<div class="container-fluid">
				<a class="navbar-brand" href="#"><i class="bi bi-book"></i></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarColor02">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<a class="nav-link app-nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>

						</li>

						@if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
						{
							<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle app-nav-link" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content management</a>
							<div class="dropdown-menu">
								<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
								<a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover type</a>
								<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
							</div>
						</li>
						}
					

					<li class="nav-item ">
							<a class="nav-link app-nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index" asp-route-status="all">
								Manage Order
							</a>

						</li>
						@if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart) != null)
						{
							<li class="nav-item">
								<a class="nav-link app-nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
									<i class="bi bi-cart2"></i>&nbsp;
									(@HttpContextAccessor.HttpContext.Session.GetInt32(SD.SessionCart))
								</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a class="nav-link app-nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
									<i class="bi bi-cart2"></i>&nbsp;
									(0)
								</a>
							</li>
						}
					</ul>
					<partial name="_LoginPartial" />
					@*      <form class="d-flex">
						<input class="form-control me-sm-2" type="text" placeholder="Search">
						<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
						</form>*@
				</div>
			</div>
		</nav>

	</header>

	<div class="app-parent">
		<main role="main">
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

@*	<footer class="border-top footer text-muted bg-dark">
		<div class="container">
			&copy; 2022 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>*@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<!-- JavaScript Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js "></script>
	<script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.tiny.cloud/1/01d6nhrhvt5o6ysaiyl87pcmb2nvx8mqkx6duktlkamyfyjw/tinymce/6/tinymce.min.js"
	referrerpolicy="origin"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js "></script>
    <script type="text/javascript">
       toastr.success('@TempData["success"]');
    </script>
  
}
@if(TempData["error"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js "></script>
    <script type="text/javascript">
       toastr.error('@TempData["error"]');
    </script>
}